export const mockData = {
  theme: {
    primary_color: "#3b82f6",
    secondary_color: "#1e40af",
    logo_url: "",
    site_name: "Appnity Softwares",
  },
  navigation: [
    { title: "About", path: "/about" },
    { title: "Portfolio", path: "/portfolio" },
    { title: "Services", path: "/services" },
    { title: "Portfolio", path: "/portfolio" },
    { title: "Team", path: "/team" },
    { title: "Contact", path: "/contact" },
  ],
  team: [
    {
      id: "1",
      full_name: "Saurabh Jain",
      role: "CEO & Founder",
      bio: "Leading the business strategy and growth. Committed to building Appnity into a premier global engineering house.",
      photo: "",
      social_links: {
        github: "https://github.com/jsaurabh334",
      },
    },
    {
      id: "2",
      full_name: "Pradip Kumar",
      role: "Managing Director",
      bio: "Overseeing operational excellence and strategic partnerships. Ensuring absolute precision in project delivery.",
      photo: "",
      social_links: {
      },
    },
    {
      id: "3",
      full_name: "Lelin Helina Tandon",
      role: "Head of Human Resources",
      bio: "Building a culture of excellence and senior-grade engineering talent. Managing global operations and team growth.",
      photo: "",
      social_links: {
        linkedin: "https://www.linkedin.com/in/helina-tandan-27b9b93b9",
      },
    },
    {
      id: "4",
      full_name: "Neha Mourya",
      role: "Full Stack Developer",
      bio: "Specialist in React, Node.js and distributed systems. Crafting seamless user experiences with robust backend logic.",
      photo: "",
      social_links: {
        github: "https://github.com/nehamoury",
        linkedin: "https://www.linkedin.com/in/nehamourya/",
      },
    },
    {
      id: "6",
      full_name: "Jatin Kurrey",
      role: "SDE & R&D",
      bio: "Focusing on core software development and research into emerging UI/UX architectures. Delivering high-performance digital systems.",
      photo: "",
      social_links: {
        github: "https://github.com/jatin-kurrey",
        linkedin: "https://www.linkedin.com/in/jatin-kurrey-07a046251",
      },
    },
  ],
  values: [
    {
      id: "1",
      icon: "Target",
      title: "Extreme Ownership",
      description: "We don't just write code; we take responsibility for the business outcome. If something isn't right, we fix it.",
    },
    {
      id: "2",
      icon: "Zap",
      title: "Speed with Precision",
      description: "We move fast, but we never compromise on quality. Automated testing and senior oversight are non-negotiable.",
    },
    {
      id: "3",
      icon: "Heart",
      title: "Radical Candor",
      description: "We tell you what you need to hear, not what you want to hear. Honesty is the foundation of our partnership.",
    },
  ],
  portfolios: [
    {
      id: "1",
      title: "Chhattisgarh Shadi",
      slug: "chhattisgarh-shadi",
      category: "Mobile Application",
      industry: "Social",
      stack: "React Native + Node.js",
      description: "A community-focused matrimonial platform built for Chhattisgarh. Features real-time matching, profile verification, and secure chat.",
      project_url: "https://chhattisgarhshadi.com",
      metrics: [
        { label: "Active Users", metric: "10k+" },
        { label: "Match Rate", metric: "52%" },
      ],
      featured: true,
    },
    {
      id: "2",
      title: "Mitaan Express",
      slug: "mitaan-express",
      category: "News Portal",
      industry: "Media",
      stack: "Next.js + Go",
      description: "High-performance news website for Shri Dhar Rao. Real-time content updates, intuitive categorization, and optimized for speed.",
      project_url: "https://mitaanexpress.com",
      metrics: [
        { label: "Monthly Readers", metric: "50k+" },
        { label: "Page Load", metric: "0.9s" },
      ],
      featured: true,
    },
    {
      id: "3",
      title: "Shri Dhar Rao Portfolio",
      slug: "shri-dhar-rao-portfolio",
      category: "Personal Brand",
      industry: "Professional Services",
      stack: "Next.js + Tailwind",
      description: "Official professional portfolio for Shri Dhar Rao. A minimal, authority-driven design showcasing personal and political achievements.",
      project_url: "https://shridharrao.com",
      metrics: [
        { label: "Page Speed", metric: "98/100" },
        { label: "Uptime", metric: "99.99%" },
      ],
      featured: true,
    },
    {
      id: "4",
      title: "Crova",
      slug: "crova",
      category: "Premium Showcase",
      industry: "Fashion & Lifestyle",
      stack: "Next.js + Shopify",
      description: "A high-end boutique showcase for handcrafted embroidery and apparel. Built with a focus on minimal design and heritage craftsmanship.",
      project_url: "https://crova.in",
      metrics: [
        { label: "Conversion", metric: "+32%" },
        { label: "Avg. Session", metric: "4m 12s" },
      ],
      featured: true,
    },
  ],
  services: [
    {
      id: "1",
      title: "Sales Growth Engine",
      description: "Stop losing leads. Organize your sales process and close deals faster with automated follow-ups.",
      icon: "Users",
      features: ["Lead Organizer", "Auto Follow-ups", "Sales Reports"],
    },
    {
      id: "2",
      title: "Knowledge & Training Hub",
      description: "Train your employees or students anywhere in the world with a professional learning platform.",
      icon: "BookOpen",
      features: ["Video Lessons", "Student Progress", "Mobile App"],
    },
    {
      id: "3",
      title: "Subscription Business",
      description: "Launch your own 'Netflix' or 'Spotify' style business with built-in recurring payments.",
      icon: "Layers",
      features: ["Easy Payments", "User Accounts", "Growth Ready"],
    },
    {
      id: "4",
      title: "Modern School Manager",
      description: "Manage admissions, fees, and results from a single dashboard. No more manual paperwork.",
      icon: "School",
      features: ["Fee Collection", "Smart Reports", "Parent App"],
    },
    {
      id: "5",
      title: "Property & Real Estate",
      description: "Showcase your properties beautifully and manage inquiries effortlessly on one site.",
      icon: "Building2",
      features: ["Property Gallery", "Agent Portal", "Map Search"],
    },
    {
      id: "6",
      title: "Vendor Marketplace",
      description: "Build your own Amazon or Flipkart. Let multiple sellers list products on your platform.",
      icon: "ShoppingCart",
      features: ["Seller Dashboard", "Admin Control", "Easy Payouts"],
    },
  ],
  faqs: [
    {
      id: "1",
      question: "How long does a typical project take?",
      answer: "Most MVP systems ship within 6-8 weeks. Larger enterprise platforms can take 3-5 months. We work in 2-week sprints so you see progress constantly.",
    },
    {
      id: "2",
      question: "Do you provide post-launch support?",
      answer: "Yes. We offer managed cloud maintenance and 'Fractional CTO' services to ensure your systems remain secure and scalable as you grow.",
    },
    {
      id: "3",
      question: "Will I own the code?",
      answer: "Absolutely. Once the final payment is made, you own 100% of the IP and the source code. No vendor lock-in, ever.",
    },
    {
      id: "4",
      question: "How do we communicate during development?",
      answer: "We set up a dedicated Slack channel for your team and conduct weekly video demos. You'll have direct access to the senior engineers working on your project.",
    },
    {
      id: "5",
      question: "Can you help me migrate from a legacy system?",
      answer: "Yes, we specialize in legacy modernization—moving your old systems to modern, cloud-native architectures without losing data or causing downtime.",
    },
  ],
  pricing: [
    {
      id: "1",
      name: "Digital Presence",
      plan_name: "Digital Presence",
      price: "₹25,000",
      price_inr: 25000,
      billing_period: "starting at",
      description: "Premium static websites and high-performance landing pages for elite brands.",
      features: [
        "Custom UI/UX Design",
        "Next.js Static Export",
        "Perfect Lighthouse Score",
        "SEO & Metadata Hardening",
        "CMS Integration (Optional)",
        "CDN Global Deployment",
      ],
      is_highlighted: false,
    },
    {
      id: "2",
      name: "Dynamic Systems",
      plan_name: "Dynamic Systems",
      price: "₹85,000",
      price_inr: 85000,
      billing_period: "starting at",
      description: "Full-stack digital products, SaaS MVPs, and complex web applications.",
      features: [
        "Custom Web Application",
        "Database Architecture",
        "Auth & Security Protocols",
        "API Development (REST/GraphQL)",
        "Cloud Infrastructure Setup",
        "3 Months Post-Launch Support",
      ],
      is_highlighted: true,
    },
    {
      id: "3",
      name: "Enterprise Solutions",
      plan_name: "Enterprise Solutions",
      price: "Custom",
      price_inr: 0,
      billing_period: "quote based",
      description: "Custom engineering for large-scale distributed systems and AI pipelines.",
      features: [
        "Distributed Architecture",
        "Legacy System Migration",
        "AI & Data Engineering",
        "Security Audits & Hardening",
        "Dedicated Engineering Unit",
        "On-prem / Hybrid Deployment",
      ],
      is_highlighted: false,
    },
  ],
  testimonials: [
    {
      id: "1",
      name: "Rashmeet Kaur",
      role: "CEO, Crova",
      company: "Crova",
      quote: "Building a custom wardrobe management system was a huge challenge. Appnity delivered a solution that is both technically robust and beautiful. Their attention to detail is exceptional.",
      content: "Building a custom wardrobe management system was a huge challenge. Appnity delivered a solution that is both technically robust and beautiful. Their attention to detail is exceptional.",
    },
    {
      id: "2",
      name: "Jaideep Gupta",
      role: "Founder, Chhatisgarh Shadi",
      company: "Chhatisgarh Shadi",
      quote: "For a platform as personal as matrimonial services, we needed a partner who understood both technology and trust. Appnity built a secure, high-performance system.",
      content: "For a platform as personal as matrimonial services, we needed a partner who understood both technology and trust. Appnity built a secure, high-performance system.",
    },
    {
      id: "3",
      name: "Prateek Tatode",
      role: "CTO, GrowthHub",
      company: "GrowthHub",
      quote: "Transparent, fast, and professional. The team at Appnity feels like an extension of our own engineering department. They truly architect excellence.",
      content: "Transparent, fast, and professional. The team at Appnity feels like an extension of our own engineering department. They truly architect excellence.",
    },
    {
      id: "4",
      name: "Shridhar Rao",
      role: "Editor, Mitaan Express",
      company: "Mitaan Express",
      quote: "Delivering absolute precision was key for my personal brand. Appnity shipped a high-performance site that exceeds all my expectations in terms of speed and UI.",
      content: "Delivering absolute precision was key for my personal brand. Appnity shipped a high-performance site that exceeds all my expectations in terms of speed and UI.",
    },
  ],
  capabilities: [
    { id: "1", title: "Web Platforms", description: "High-performance React/Next.js applications." },
    { id: "2", title: "Mobile Apps", description: "Cross-platform React Native solutions." },
    { id: "3", title: "Cloud Infrastructure", description: "Secure and scalable AWS/Google Cloud setups." },
  ],
  process: [
    { step: "01", title: "Blueprint", description: "Architecture and technical planning." },
    { step: "02", title: "Build", description: "Iterative development and testing." },
    { step: "03", title: "Ship", description: "Cloud deployment and hardening." },
  ],
};
